#!/usr/bin/env bash

docker build -t trial .

docker rm $(docker ps -a -f status=exited -q)

docker run -d --name rabbitGoContainer -p 15672:15672 -p 5672:5672 -p 8080:8080 trial

(
  sleep 15;
  docker exec -d rabbitGoContainer ./rabbitmqPublisher;
)
